export enum TASK_REDUCER_TYPES {
  FETCH_TASKS = 'FETCH_TASKS',
  ADD_TASK = 'ADD_TASK',
  TOGGLE_TASK_COMPLETION = 'TOGGLE_TASK_COMPLETION',
  DELETE_TASK = 'DELETE_TASK',
  SET_STATE_FROM_STORAGE = 'SET_STATE_FROM_STORAGE',
  SET_LOADING = 'SET_LOADING',
  SET_ERROR = 'SET_ERROR',
}
